### ISSUE TITLE
Foundry 10 Compatibility Issues

### ISSUE THREAD

**Issue by tinwatchman** [Ch1sKey/foundry-grid-numbers#2]
Hey - so I'm playing in a game that uses this module. (Thank you, by the way.) According to my GM, though, it's not currently working with the new version of Foundry. I can try to get more details on what the problem is from him if you want. If you don't have time to upgrade things right now, I get it. In that case, would you be okay with me looking into it myself and submitting a merge request if I figure it out? Let me know.

**Comment by Ch1sKey** [comment]
Hey, thanks for reaching out. I'll work on compatibility with the 10s version at the nearest time.
A lot of stuff changes so I need a bit of time to figure out how to fix it and publish it.

**Comment by Ch1sKey** [comment]
Done. v1.1.3 is compatible with V10
